* ET-312 Programs and Modules
** Introduction
This document contains notes about how programs and modules work.  You need to be
familiar with the memory layout and refer to
[[https://github.com/metafetish/buttshock-protocol-docs/blob/master/doc/et312-protocol.org][ET312 Protocol Documentation]].

*** Terminology

- A Program is either an Internal or Use Uploaded program.  Examples of Programs are "Waves", "Phase 2", "User 1".
- Each Program is made up of a number of Modules.
- Each Module contains a variable number of Instructions.
- The Instruction set is very limited, mostly just allowing certain memory operations.

*** Loading a Program (inbuilt Programs)

- As a user you select a program name using the buttons on the box
- This runs "calltable 22" with the program number
- The firmware will set up some defaults into the memory locations 0x80+ (channel A) and 0x180+ (channel B) that are the same for every program
- The firmware has a hardcoded mapping for the given Program to which Module gets loaded.
- This runs "calltable 30" with the module number
- The Instructions from that Module are parsed, one by one.
- Each Instruction will read or write or manipulate memory (specifically the 0x80+ and 0x180+ locations)
- A second Module may then get parsed depending on the Program.  This is to handle the complexities of allowing a mode to be "Split" an run different Programs on A and B channels.
- There's also a little bit of additional hardcoding going on in the firmware to handle the "Random 1" mode and audio modes.

The Modules do not stay running continuously, they are only used to do an set up of memory locations.  Changes that then
happen (like intensity changes, frequency changes) all take place based on the counters and timers and other memory
settings.

Modules can however set up triggers that can cause Modules to get run at some later point, so for example a Module could set
up one of the timers to run, and when the timer reaches some value it causes a different
Module to then get loaded.  The "Rhythm" mode for example cycles between three different Modules in this way.

You can use the utility "module-decode.py" in this repo to display the Instructions for a given Module, both in-built
using the firmware image, or by examining the memory on a box.  For example:

#+BEGIN_EXAMPLE
$ python3 module-decode.py -i ../firmware/312-16-decrypted.bin -d ../../buttshock-protocol-docs/doc/et312-protocol.org -m 11 
#+END_EXAMPLE

*** Defaults

[[https://github.com/metafetish/buttshock-protocol-docs/blob/master/doc/et312-protocol.org#409c-40bf---main-variables][Main variables]]

*** Program "Waves" is Modules 11, 12

If you select Program "Waves" then the firmware loads Module 11.  Module 11 contains these Instructions:

#+BEGIN_EXAMPLE
memory[0086 *Multi Adjust Range Min* (0x0f)]=01
memory[0087 *Multi Adjust Range Max* (0xff)]=40
memory[00be *Channel A: Current Width Modulation Select* (0x04)]=41
memory[00bb *Channel A: Current Width Modulation Increment* (0x01)]=02
memory[00b5 *Channel A: Current Frequency Modulation Select* (0x08)]=41
memory[00b0 *Channel A: Current Frequency Modulation Max* (0x64)]=80
#+END_EXAMPLE

If the user is not using the Split mode, for Program "Waves" the firmware will then also load Module 12.
Module 12 contains these Instructions:

#+BEGIN_EXAMPLE
memory[01bb *Channel B: Current Width Modulation Increment* (0x01)]=03
memory[01b0 *Channel B: Current Frequency Modulation Max* (0x64)]=40
#+END_EXAMPLE

[[https://github.com/metafetish/buttshock-protocol-docs/blob/master/doc/et312-protocol.org#example][See how this interacts with the defaults to create the actual output.]]

*** Program "Stroke" is Modules 3, 4

If you select Program "Stroke" then the firmware loads Module 3.  Module 3 contains these Instructions:

#+BEGIN_EXAMPLE
memory[00a9 *Channel A: Current Intensity Modulation Step* (0x01)]=02
memory[00ac *Channel A: Current Intensity Modulation Select* (0x00)]=55
memory[00b5 *Channel A: Current Frequency Modulation Select* (0x08)]=00
memory[0086 *Multi Adjust Range Min* (0x0f)]=00
memory[0087 *Multi Adjust Range Max* (0xff)]=20
memory[0090 *Channel A: Current Gate Value* (0x06)]=05
memory[00aa *Channel A: Current Intensity Action at Min* (0xff)]=fe
memory[00ab *Channel A: Current Intensity Action at Max* (0xff)]=fe
memory[00be *Channel A: Current Width Modulation Select* (0x04)]=00
memory[00b7 *Channel A: Current Width Modulation Value* (0x82)]=ff
#+END_EXAMPLE

So this

- Sets the MA knob range from 0x00 to 0x20
- A Intensity: changes in steps of *0x02* over the range of minimum to 0xff, using the *244Hz timer*.  Rate is *from the MA knob*.  Minimum (default 0xcd) is set to inverse of the advanced parameter default for Intensity.  When reaching the maximum or minimum the A output *toggles and reverses direction*.
- A Frequency: changes in steps of 0x01, rate 0x01 in the range 0x09 to 0x64, the frequency *does not change by the MA knob*.
- A Width: changes in steps of 0x01, rate 0x01 in the range 0x32 to 0xc8, reversing at minimum and maximum.  (Why does it set the starting value to 0xff?).  Does *not use the advance parameter default*.

If the user is not using the Split mode, the firmware will then also load Module 4.
Module 4 contains these Instructions:

#+BEGIN_EXAMPLE
memory[01ac *Channel B: Current Intensity Modulation Select* (0x00)]=41
memory[01a6 *Channel B: Current Intensity Modulation Min* (0xcd)]=e6
memory[01b7 *Channel B: Current Width Modulation Value* (0x82)]=d8
memory[01a9 *Channel B: Current Intensity Modulation Step* (0x01)]=01
#+END_EXAMPLE

This

- B Intensity: changes in steps of 0x01, rate 0x01 in range *0xe6* to 0xff, using the *244Hz timer*.  Rate is *from the MA knob*.  Minimum
doesn't change.
- B Width: *follows the inverse of the current MA knob value*.
- B Frequency: set to the value of the advanced_parameter default

*** Program to Module list

| Program | Modules                    |
|---------------+---------------------------------|
| waves  | 11 (A) 12 (B) |
| stroke |  3 (A)  4 (B) |
| climb  |  5 (A)  8 (B) |
| combo  | 13 (A) 33 (B) |
| intense| 14 (A)  2 (B) |
| rhythm | 15 (triggers run 16, 17) |
| audio  | 23 |
| audio3 | 34 |
| random2| 32 (triggers load 32 again) |
| toggle | 18 (triggers run 19) |
| orgasm | 24 (triggers run 25, 26, 27) |
| torment| 28 |
| phase  | 20 and 21 and 35 |
| phase3 | 22 |
| random1| special hardcoded |

